AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: sam-build-test
    Description: todo
    Author: NathanYocum
    HomePageUrl: https://nathanyocum.com
    SourceCodeUrl: https://nathanyocum.com

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.handler
      Runtime: python3.7